name = "Fortran"
grammar = "fortran"
path_suffixes = [
    "f",
    "for",
    "ftn",
    "f77",
    "f90",
    "f95",
    "f03",
    "f08",
    "f18",
    "F",
    "FOR",
    "FTN",
    "F77",
    "F90",
    "F95",
    "F03",
    "F08",
    "F18",
]
line_comments = ["! "]
